// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/hub.proto

package proto

import (
	"context"
	"fmt"

	"google.golang.org/grpc"
)

type MessageType int32

const (
	MessageType_DIRECT    MessageType = 0
	MessageType_BROADCAST MessageType = 1
	MessageType_CHANNEL   MessageType = 2
	MessageType_REGISTER  MessageType = 3 // NEW
	MessageType_REQUEST   MessageType = 4 // NEW
	MessageType_RESPONSE  MessageType = 5 // NEW
)

type RequestType int32

const (
	RequestType_JSON    RequestType = 0
	RequestType_FILE    RequestType = 1
	RequestType_CONTROL RequestType = 2
)

type Status int32

const (
	Status_OK    Status = 0
	Status_ERROR Status = 1
)

type Message struct {
	Id        string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From      string            `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To        string            `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Channel   string            `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	Content   string            `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp string            `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type      MessageType       `protobuf:"varint,7,opt,name=type,proto3,enum=hub.MessageType" json:"type,omitempty"`
	Action    string            `protobuf:"bytes,8,opt,name=action,proto3" json:"action,omitempty"`
	Metadata  map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return fmt.Sprintf("%+v", *m) }
func (m *Message) ProtoMessage()  {}

type Request struct {
	Type RequestType `protobuf:"varint,1,opt,name=type,proto3,enum=hub.RequestType" json:"type,omitempty"`
	Data string      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (r *Request) Reset()         { *r = Request{} }
func (r *Request) String() string { return fmt.Sprintf("%+v", *r) }
func (r *Request) ProtoMessage()  {}

type Response struct {
	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=hub.Status" json:"status,omitempty"`
	Data   string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (r *Response) Reset()         { *r = Response{} }
func (r *Response) String() string { return fmt.Sprintf("%+v", *r) }
func (r *Response) ProtoMessage()  {}

type HubServiceClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (HubService_ConnectClient, error)
}

type HubService_ConnectClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type HubServiceServer interface {
	Connect(HubService_ConnectServer) error
}

type HubService_ConnectServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

func RegisterHubServiceServer(s grpc.ServiceRegistrar, srv HubServiceServer) {
	s.RegisterService(&grpc.ServiceDesc{
		ServiceName: "hub.HubService",
		HandlerType: (*HubServiceServer)(nil),
		Methods:     []grpc.MethodDesc{},
		Streams: []grpc.StreamDesc{
			{
				StreamName:    "Connect",
				Handler:       _HubService_Connect_Handler,
				ServerStreams: true,
				ClientStreams: true,
			},
		},
		Metadata: "hub.proto",
	}, srv)
}

func _HubService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HubServiceServer).Connect(&hubServiceConnectServer{stream})
}

type hubServiceConnectServer struct {
	grpc.ServerStream
}

func (x *hubServiceConnectServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hubServiceConnectServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func NewHubServiceClient(cc grpc.ClientConnInterface) HubServiceClient {
	// Implementation would be generated
	return &hubServiceClient{cc}
}

type hubServiceClient struct {
	cc grpc.ClientConnInterface
}

func (c *hubServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (HubService_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &grpc.StreamDesc{
		StreamName:    "connect",
		ServerStreams: true,
		ClientStreams: true,
	}, "/hub.HubService/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &hubServiceConnectClient{stream}
	return x, nil
}

type hubServiceConnectClient struct {
	grpc.ClientStream
}

func (x *hubServiceConnectClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hubServiceConnectClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}