// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: proto/hub.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HubServiceClient is the client API for HubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HubServiceClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (HubService_ConnectClient, error)
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (HubService_UploadFileClient, error)
	DownloadFile(ctx context.Context, in *FileDownloadRequest, opts ...grpc.CallOption) (HubService_DownloadFileClient, error)
}

type hubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHubServiceClient(cc grpc.ClientConnInterface) HubServiceClient {
	return &hubServiceClient{cc}
}

func (c *hubServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (HubService_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &HubService_ServiceDesc.Streams[0], "/hub.HubService/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &hubServiceConnectClient{stream}
	return x, nil
}

type HubService_ConnectClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type hubServiceConnectClient struct {
	grpc.ClientStream
}

func (x *hubServiceConnectClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hubServiceConnectClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hubServiceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (HubService_UploadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &HubService_ServiceDesc.Streams[1], "/hub.HubService/UploadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &hubServiceUploadFileClient{stream}
	return x, nil
}

type HubService_UploadFileClient interface {
	Send(*FileChunk) error
	CloseAndRecv() (*FileUploadResponse, error)
	grpc.ClientStream
}

type hubServiceUploadFileClient struct {
	grpc.ClientStream
}

func (x *hubServiceUploadFileClient) Send(m *FileChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hubServiceUploadFileClient) CloseAndRecv() (*FileUploadResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(FileUploadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hubServiceClient) DownloadFile(ctx context.Context, in *FileDownloadRequest, opts ...grpc.CallOption) (HubService_DownloadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &HubService_ServiceDesc.Streams[2], "/hub.HubService/DownloadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &hubServiceDownloadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HubService_DownloadFileClient interface {
	Recv() (*FileChunk, error)
	grpc.ClientStream
}

type hubServiceDownloadFileClient struct {
	grpc.ClientStream
}

func (x *hubServiceDownloadFileClient) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HubServiceServer is the server API for HubService service.
// All implementations should embed UnimplementedHubServiceServer
// for forward compatibility
type HubServiceServer interface {
	Connect(HubService_ConnectServer) error
	UploadFile(HubService_UploadFileServer) error
	DownloadFile(*FileDownloadRequest, HubService_DownloadFileServer) error
}

// UnimplementedHubServiceServer should be embedded to have forward compatible implementations.
type UnimplementedHubServiceServer struct {
}

func (UnimplementedHubServiceServer) Connect(HubService_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedHubServiceServer) UploadFile(HubService_UploadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedHubServiceServer) DownloadFile(*FileDownloadRequest, HubService_DownloadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}

// UnsafeHubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HubServiceServer will
// result in compilation errors.
type UnsafeHubServiceServer interface {
	mustEmbedUnimplementedHubServiceServer()
}

func RegisterHubServiceServer(s grpc.ServiceRegistrar, srv HubServiceServer) {
	s.RegisterService(&HubService_ServiceDesc, srv)
}

func _HubService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HubServiceServer).Connect(&hubServiceConnectServer{stream})
}

type HubService_ConnectServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type hubServiceConnectServer struct {
	grpc.ServerStream
}

func (x *hubServiceConnectServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hubServiceConnectServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _HubService_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HubServiceServer).UploadFile(&hubServiceUploadFileServer{stream})
}

type HubService_UploadFileServer interface {
	SendAndClose(*FileUploadResponse) error
	Recv() (*FileChunk, error)
	grpc.ServerStream
}

type hubServiceUploadFileServer struct {
	grpc.ServerStream
}

func (x *hubServiceUploadFileServer) SendAndClose(m *FileUploadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hubServiceUploadFileServer) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _HubService_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileDownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HubServiceServer).DownloadFile(m, &hubServiceDownloadFileServer{stream})
}

type HubService_DownloadFileServer interface {
	Send(*FileChunk) error
	grpc.ServerStream
}

type hubServiceDownloadFileServer struct {
	grpc.ServerStream
}

func (x *hubServiceDownloadFileServer) Send(m *FileChunk) error {
	return x.ServerStream.SendMsg(m)
}

// HubService_ServiceDesc is the grpc.ServiceDesc for HubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hub.HubService",
	HandlerType: (*HubServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _HubService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadFile",
			Handler:       _HubService_UploadFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _HubService_DownloadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/hub.proto",
}
