# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hub.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hub.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\thub.proto\x12\x03hub\"\xf3\x01\n\x07Message\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x66rom\x18\x02 \x01(\t\x12\n\n\x02to\x18\x03 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\t\x12\x1e\n\x04type\x18\x07 \x01(\x0e\x32\x10.hub.MessageType\x12\x0e\n\x06\x61\x63tion\x18\x08 \x01(\t\x12,\n\x08metadata\x18\t \x03(\x0b\x32\x1a.hub.Message.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xd4\x01\n\x12WorkerRegistration\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x13\n\x0bworker_type\x18\x02 \x01(\t\x12,\n\x0c\x63\x61pabilities\x18\x03 \x03(\x0b\x32\x16.hub.ServiceCapability\x12\x37\n\x08metadata\x18\x04 \x03(\x0b\x32%.hub.WorkerRegistration.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"c\n\x11ServiceCapability\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x14\n\x0cinput_schema\x18\x03 \x01(\t\x12\x15\n\routput_schema\x18\x04 \x01(\t\"7\n\x07Request\x12\x1e\n\x04type\x18\x01 \x01(\x0e\x32\x10.hub.RequestType\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"5\n\x08Response\x12\x1b\n\x06status\x18\x01 \x01(\x0e\x32\x0b.hub.Status\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t*^\n\x0bMessageType\x12\n\n\x06\x44IRECT\x10\x00\x12\r\n\tBROADCAST\x10\x01\x12\x0b\n\x07\x43HANNEL\x10\x02\x12\x0c\n\x08REGISTER\x10\x03\x12\x0b\n\x07REQUEST\x10\x04\x12\x0c\n\x08RESPONSE\x10\x05*.\n\x0bRequestType\x12\x08\n\x04JSON\x10\x00\x12\x08\n\x04\x46ILE\x10\x01\x12\x0b\n\x07\x43ONTROL\x10\x02*\x1b\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x32\x37\n\nHubService\x12)\n\x07\x43onnect\x12\x0c.hub.Message\x1a\x0c.hub.Message(\x01\x30\x01\x42\x39\n\x0f\x63om.deepapp.hubZ&deepapp_golang_grpc_hub/internal/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.deepapp.hubZ&deepapp_golang_grpc_hub/internal/proto'
  _globals['_MESSAGE_METADATAENTRY']._loaded_options = None
  _globals['_MESSAGE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_WORKERREGISTRATION_METADATAENTRY']._loaded_options = None
  _globals['_WORKERREGISTRATION_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_MESSAGETYPE']._serialized_start=692
  _globals['_MESSAGETYPE']._serialized_end=786
  _globals['_REQUESTTYPE']._serialized_start=788
  _globals['_REQUESTTYPE']._serialized_end=834
  _globals['_STATUS']._serialized_start=836
  _globals['_STATUS']._serialized_end=863
  _globals['_MESSAGE']._serialized_start=19
  _globals['_MESSAGE']._serialized_end=262
  _globals['_MESSAGE_METADATAENTRY']._serialized_start=215
  _globals['_MESSAGE_METADATAENTRY']._serialized_end=262
  _globals['_WORKERREGISTRATION']._serialized_start=265
  _globals['_WORKERREGISTRATION']._serialized_end=477
  _globals['_WORKERREGISTRATION_METADATAENTRY']._serialized_start=215
  _globals['_WORKERREGISTRATION_METADATAENTRY']._serialized_end=262
  _globals['_SERVICECAPABILITY']._serialized_start=479
  _globals['_SERVICECAPABILITY']._serialized_end=578
  _globals['_REQUEST']._serialized_start=580
  _globals['_REQUEST']._serialized_end=635
  _globals['_RESPONSE']._serialized_start=637
  _globals['_RESPONSE']._serialized_end=690
  _globals['_HUBSERVICE']._serialized_start=865
  _globals['_HUBSERVICE']._serialized_end=920
# @@protoc_insertion_point(module_scope)
